services:
  restapi:
    image: ai25m060/restapi:latest   
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:mysecurepw123@db:5432/postgres
    depends_on:
      - db
    volumes:
    - ./src:/app/src
    command: uvicorn src.fast_api:app --host 0.0.0.0 --port 8000 --reload
    #iâ†‘ this runs FastAPI with auto reload

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersafepw1+
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"

volumes:
  postgres_data:
